import Mathlib
import MinimalSufficientFutureStateKernelV1
import BayesAdaptiveKernelV1

namespace InsacermoBeliefPolicySufficientFutureState

open InsacermoMinimalSufficientFutureState
open Insacermo.BayesAdaptiveKernel

universe th s a o r

/-- A finite adaptive policy over belief states. `probe a next` branches on the
observation generated by action `a`; `repair` transforms the current belief. -/
inductive AdaptivePolicy
    (Theta : Type th) (S : Type s) (A : Type a) (O : Type o)
    [Fintype Theta] [Fintype S]
  | act (a : A)
  | refuse
  | probe (a : A) (next : O → AdaptivePolicy Theta S A O)
  | repair (step : Belief Theta S → Belief Theta S)
      (next : AdaptivePolicy Theta S A O)

/-- Full finite behavior tree exposed by an adaptive policy. Chance nodes retain
both the predictive observation law and every observation-contingent future. -/
inductive BehaviorTree (A : Type a) (O : Type o)
  | acted (a : A)
  | refused
  | chance (prob : O → ℝ) (next : O → BehaviorTree A O)

/-- Contract semantics on belief states. -/
structure BeliefSemantics
    (Theta : Type th) (S : Type s) (A : Type a) (O : Type o)
    [Fintype Theta] [Fintype S] [Fintype O] where
  transition : TransitionKernel Theta S A
  observation : ObservationKernel Theta S A O
  legalAct : Belief Theta S → A → Prop
  legalActDecidable : ∀ b a, Decidable (legalAct b a)

/-- Totalized Bayes step. On every positive-evidence branch this is exactly the
verified normalized Bayes update. Zero-evidence branches retain the prior belief;
they carry probability zero in the behavior tree and therefore cannot affect its
induced probability law. -/
noncomputable def totalBayesUpdate
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (b : Belief Theta S) (a : A) (o : O) : Belief Theta S := by
  classical
  exact if h : 0 < evidence b sem.transition sem.observation a o then
    bayesUpdate b sem.transition sem.observation a o h
  else b

/-- Positive-evidence branches use the historical kernel-verified Bayes update
without modification. -/
theorem totalBayesUpdate_eq_bayesUpdate_of_pos
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (b : Belief Theta S) (a : A) (o : O)
    (h : 0 < evidence b sem.transition sem.observation a o) :
    totalBayesUpdate sem b a o =
      bayesUpdate b sem.transition sem.observation a o h := by
  classical
  unfold totalBayesUpdate
  simp only [dif_pos h]
  congr

/-- Execute a finite adaptive policy from a belief state. A probe exposes the
full predictive law and recursively evaluates every observation-contingent
continuation from the corresponding Bayes-updated belief. -/
noncomputable def runAdaptivePolicy
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O) :
    Belief Theta S → AdaptivePolicy Theta S A O → BehaviorTree A O
  | b, .act a => by
      letI : Decidable (sem.legalAct b a) := sem.legalActDecidable b a
      exact if sem.legalAct b a then .acted a else .refused
  | _, .refuse => .refused
  | b, .probe a next =>
      .chance
        (fun o => evidence b sem.transition sem.observation a o)
        (fun o => runAdaptivePolicy sem (totalBayesUpdate sem b a o) (next o))
  | b, .repair step next => runAdaptivePolicy sem (step b) next
termination_by
  b p => p

/-- Two beliefs are policy-equivalent when every finite Bayes-adaptive
ACT/PROBE/REPAIR/REFUSE policy generates exactly the same probabilistic behavior
tree from both. -/
def BeliefPolicyEq
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (b₁ b₂ : Belief Theta S) : Prop :=
  FutureEq (fun b p => runAdaptivePolicy sem b p) b₁ b₂

/-- Canonical belief-policy state: complete behavior signature against every
finite adaptive policy. -/
def CanonicalBeliefPolicyState
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O) (b : Belief Theta S) :
    AdaptivePolicy Theta S A O → BehaviorTree A O :=
  CanonicalFutureState (fun b p => runAdaptivePolicy sem b p) b

/-- Canonical-state equality is exactly Bayes-adaptive policy equivalence. -/
theorem canonicalBeliefPolicyState_eq_iff
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (b₁ b₂ : Belief Theta S) :
    CanonicalBeliefPolicyState sem b₁ = CanonicalBeliefPolicyState sem b₂ ↔
      BeliefPolicyEq sem b₁ b₂ := by
  exact canonicalFutureState_eq_iff_futureEq
    (fun b p => runAdaptivePolicy sem b p) b₁ b₂

/-- Every representation safe for all Bayes-adaptive policies refines the
canonical belief-policy kernel. -/
theorem beliefPolicySafe_iff_kernel_refines_canonical
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o} {Rep : Type r}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (h : Belief Theta S → Rep) :
    FutureSafeRepresentation (fun b p => runAdaptivePolicy sem b p) h ↔
      ∀ b₁ b₂, h b₁ = h b₂ →
        CanonicalBeliefPolicyState sem b₁ = CanonicalBeliefPolicyState sem b₂ := by
  exact futureSafe_iff_kernel_refines_canonical
    (fun b p => runAdaptivePolicy sem b p) h

/-- Universal factorization through any representation safe for every finite
Bayes-adaptive policy. -/
theorem canonical_belief_policy_factors_through_every_safe_representation
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o} {Rep : Type r}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (h : Belief Theta S → Rep)
    (hsafe : FutureSafeRepresentation (fun b p => runAdaptivePolicy sem b p) h)
    (b : Belief Theta S) :
    DecodeCanonicalOnRange (fun b p => runAdaptivePolicy sem b p) h
      ⟨h b, ⟨b, rfl⟩⟩ = CanonicalBeliefPolicyState sem b := by
  exact canonical_factors_through_every_safe_representation
    (fun b p => runAdaptivePolicy sem b p) h hsafe b

/-- One distinguishing adaptive policy is enough to forbid a safe merge of two
belief states. -/
theorem distinguishing_adaptive_policy_forbids_safe_merge
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o} {Rep : Type r}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (h : Belief Theta S → Rep)
    (hsafe : FutureSafeRepresentation (fun b p => runAdaptivePolicy sem b p) h)
    {b₁ b₂ : Belief Theta S} (p : AdaptivePolicy Theta S A O)
    (hdiff : runAdaptivePolicy sem b₁ p ≠ runAdaptivePolicy sem b₂ p) :
    h b₁ ≠ h b₂ := by
  intro hmerge
  exact hdiff (hsafe b₁ b₂ hmerge p)

/-- Belief-state destruction/compression is safe exactly when it leaves the
canonical Bayes-adaptive future state unchanged. -/
def BeliefPolicyPreservingMap
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (d : Belief Theta S → Belief Theta S) : Prop :=
  FuturePreservingMap (fun b p => runAdaptivePolicy sem b p) d

theorem beliefPolicyPreservingMap_iff_canonical_unchanged
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O)
    (d : Belief Theta S → Belief Theta S) :
    BeliefPolicyPreservingMap sem d ↔
      ∀ b, CanonicalBeliefPolicyState sem b =
        CanonicalBeliefPolicyState sem (d b) := by
  exact futurePreservingMap_iff_canonical_unchanged
    (fun b p => runAdaptivePolicy sem b p) d

/-- BELIEF-POLICY SUFFICIENT FUTURE STATE KERNEL V1.

The minimal sufficient future-state theorem lifts to finite Bayes-adaptive
policies over verified belief states. The behavior signature retains predictive
probabilities and all observation-contingent continuations; every safe
representation factors through it; one distinguishing adaptive policy forbids a
safe merge; and belief compression/destruction is admissible exactly when the
canonical adaptive future state is unchanged. -/
theorem belief_policy_sufficient_future_state_v1
    {Theta : Type th} {S : Type s} {A : Type a} {O : Type o}
    [Fintype Theta] [Fintype S] [Fintype O]
    (sem : BeliefSemantics Theta S A O) :
    FutureSafeRepresentation
      (fun b p => runAdaptivePolicy sem b p) (CanonicalBeliefPolicyState sem) ∧
    FutureCompleteRepresentation
      (fun b p => runAdaptivePolicy sem b p) (CanonicalBeliefPolicyState sem) ∧
    (∀ {Rep : Type r} (h : Belief Theta S → Rep),
      FutureSafeRepresentation (fun b p => runAdaptivePolicy sem b p) h →
      ∀ b,
        DecodeCanonicalOnRange (fun b p => runAdaptivePolicy sem b p) h
          ⟨h b, ⟨b, rfl⟩⟩ = CanonicalBeliefPolicyState sem b) ∧
    (∀ d : Belief Theta S → Belief Theta S,
      BeliefPolicyPreservingMap sem d ↔
        ∀ b, CanonicalBeliefPolicyState sem b =
          CanonicalBeliefPolicyState sem (d b)) := by
  exact minimal_sufficient_future_state_v1
    (fun b p => runAdaptivePolicy sem b p)

end InsacermoBeliefPolicySufficientFutureState
