import Mathlib
import SilentFutureKernelV1

namespace InsacermoDynamicalHiddenDebt

open Set
open InsacermoCausalPriceFactorization
open InsacermoHigherOrderPriceInteraction
open InsacermoNoLocalAuditor
open InsacermoSilentFuture

/-- Generic autonomous discrete-time trajectory generated by one fixed transition map. -/
def trajectory {State : Type*} (step : State → State) (x₀ : State) : Nat → State
  | 0 => x₀
  | t + 1 => step (trajectory step x₀ t)

/-- Latent reserve loses one unit per autonomous transition; zero is absorbing. -/
def reserveStep (r : Nat) : Nat := r - 1

/-- The latent reserve trajectory starting from H. -/
def reserveAt (H t : Nat) : Nat := trajectory reserveStep H t

/-- Exact orbit formula for the autonomous reserve process. -/
theorem reserveAt_eq_sub (H t : Nat) :
    reserveAt H t = H - t := by
  induction t with
  | zero => simp [reserveAt, trajectory]
  | succ t ih =>
      simp [reserveAt, trajectory, reserveStep, ih]
      omega

/-- Strictly before H, latent reserve is still positive. -/
theorem reserveAt_pos_before (H t : Nat) (ht : t < H) :
    0 < reserveAt H t := by
  rw [reserveAt_eq_sub]
  omega

/-- At and after H, latent reserve is exhausted permanently. -/
theorem reserveAt_zero_at_or_after (H t : Nat) (ht : H ≤ t) :
    reserveAt H t = 0 := by
  rw [reserveAt_eq_sub]
  omega

/-- Price law attached to the CURRENT STATE only: while reserve is positive the world is flat;
when reserve is zero the hard higher-order geometry is active. No clock appears in this law. -/
noncomputable def StatePrice
    (n M r : Nat) (S : Finset (Fin n)) : Nat :=
  if r = 0 then
    SetPrice (hoCost n M) (hoSat n) S (ho_set_feasible n M S)
  else
    SetPrice flatCost (flatSat (Req := Fin n)) S (flat_set_feasible S)

/-- Dynamical debt price is obtained only by observing the state reached by autonomous iteration. -/
noncomputable def DynamicalDebtPrice
    (H n M t : Nat) (S : Finset (Fin n)) : Nat :=
  StatePrice n M (reserveAt H t) S

/-- Safe comparison world remains flat forever. -/
noncomputable def DynamicalSafePrice
    (n : Nat) (_t : Nat) (S : Finset (Fin n)) : Nat :=
  SetPrice flatCost (flatSat (Req := Fin n)) S (flat_set_feasible S)

/-- Before reserve exhaustion the complete coalition-price profile is identical to the safe world. -/
theorem full_profile_silent_before_exhaustion
    (H n M t : Nat) (ht : t < H) :
    ∀ S : Finset (Fin n),
      DynamicalDebtPrice H n M t S = DynamicalSafePrice n t S := by
  intro S
  have hr : reserveAt H t ≠ 0 := Nat.ne_of_gt (reserveAt_pos_before H t ht)
  simp [DynamicalDebtPrice, DynamicalSafePrice, StatePrice, hr]

/-- At and after exhaustion the full contract has permanent price M. -/
theorem full_price_M_after_exhaustion
    (H n M t : Nat) (ht : H ≤ t) :
    DynamicalDebtPrice H n M t Finset.univ = M := by
  have hr : reserveAt H t = 0 := reserveAt_zero_at_or_after H t ht
  simp [DynamicalDebtPrice, StatePrice, hr]
  exact full_price_eq_M n M

/-- The safe world's full price is one forever. -/
theorem safe_full_price_one_forever
    (n t : Nat) :
    DynamicalSafePrice n t Finset.univ = 1 := by
  simp [DynamicalSafePrice]
  exact flat_price_eq_one Finset.univ

/-- Even after reserve exhaustion, every coalition of order at most k remains locally identical
when k<n. -/
theorem local_profile_identical_after_exhaustion
    (H n M k t : Nat) (ht : H ≤ t) (hkn : k < n) (hM : 1 ≤ M) :
    ∀ S : Finset (Fin n), S.card ≤ k →
      DynamicalDebtPrice H n M t S = DynamicalSafePrice n t S := by
  intro S hcard
  have hr : reserveAt H t = 0 := reserveAt_zero_at_or_after H t ht
  simp [DynamicalDebtPrice, DynamicalSafePrice, StatePrice, hr]
  rw [flat_price_eq_one S]
  exact (bounded_order_audits_can_miss_global n k M hkn hM).1 S hcard

/-- In fact the ENTIRE infinite order-k observation trace is identical between the two worlds. -/
theorem infinite_local_trace_indistinguishable
    (H n M k : Nat) (hkn : k < n) (hM : 1 ≤ M) :
    ∀ t, ∀ S : Finset (Fin n), S.card ≤ k →
      DynamicalDebtPrice H n M t S = DynamicalSafePrice n t S := by
  intro t S hcard
  by_cases ht : t < H
  · exact full_profile_silent_before_exhaustion H n M t ht S
  · exact local_profile_identical_after_exhaustion
      H n M k t (Nat.le_of_not_gt ht) hkn hM S hcard

/-- Global budget-one safety induced by a temporal price process. -/
def GloballySafe
    (price : Nat → Finset (Fin n) → Nat) (t : Nat) : Prop :=
  price t Finset.univ ≤ 1

/-- Safe comparison world remains globally safe forever. -/
theorem safe_world_safe_forever (n t : Nat) :
    GloballySafe (DynamicalSafePrice n) t := by
  unfold GloballySafe
  rw [safe_full_price_one_forever n t]

/-- Before exhaustion, the debt world is globally safe under budget one. -/
theorem debt_world_safe_before_exhaustion
    (H n M t : Nat) (ht : t < H) :
    GloballySafe (DynamicalDebtPrice H n M) t := by
  unfold GloballySafe
  have hprof := full_profile_silent_before_exhaustion H n M t ht Finset.univ
  rw [hprof, safe_full_price_one_forever n t]

/-- If M>1, exhaustion creates a permanent global failure. -/
theorem debt_world_unsafe_after_exhaustion
    (H n M t : Nat) (hM : 1 < M) (ht : H ≤ t) :
    ¬ GloballySafe (DynamicalDebtPrice H n M) t := by
  unfold GloballySafe
  rw [full_price_M_after_exhaustion H n M t ht]
  omega

/-- DYNAMICAL HIDDEN DEBT: for every latent lifetime H, local audit order k and target N,
there is an autonomous deterministic system whose entire low-order observation trace is identical
to a forever-safe comparison world, while its global price remains silent before reserve exhaustion
and then becomes permanently greater than N. The critical horizon is generated by state dynamics,
not read directly by the price law. -/
theorem dynamical_hidden_debt_impossibility_v1
    (H k N : Nat) :
    ∃ n M,
      k < n ∧ N < M ∧ 1 < M ∧
      (∀ t, reserveAt H t = H - t) ∧
      (∀ t, t < H → ∀ S : Finset (Fin n),
        DynamicalDebtPrice H n M t S = DynamicalSafePrice n t S) ∧
      (∀ t, ∀ S : Finset (Fin n), S.card ≤ k →
        DynamicalDebtPrice H n M t S = DynamicalSafePrice n t S) ∧
      (∀ t, GloballySafe (DynamicalSafePrice n) t) ∧
      (∀ t, t < H → GloballySafe (DynamicalDebtPrice H n M) t) ∧
      (∀ t, H ≤ t →
        DynamicalDebtPrice H n M t Finset.univ = M ∧
        ¬ GloballySafe (DynamicalDebtPrice H n M) t) := by
  refine ⟨k + 1, max (N + 1) 2, by omega, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · omega
  · omega
  · intro t
    exact reserveAt_eq_sub H t
  · intro t ht S
    exact full_profile_silent_before_exhaustion H (k + 1) (max (N + 1) 2) t ht S
  · exact infinite_local_trace_indistinguishable
      H (k + 1) (max (N + 1) 2) k (by omega) (by omega)
  · intro t
    exact safe_world_safe_forever (k + 1) t
  · intro t ht
    exact debt_world_safe_before_exhaustion H (k + 1) (max (N + 1) 2) t ht
  · intro t ht
    constructor
    · exact full_price_M_after_exhaustion H (k + 1) (max (N + 1) 2) t ht
    · exact debt_world_unsafe_after_exhaustion
        H (k + 1) (max (N + 1) 2) t (by omega) ht

end InsacermoDynamicalHiddenDebt
